"""rename date to expense_date in expenses

Revision ID: 182343089be2
Revises: 3d919b2a4ccb
Create Date: 2026-06-03 11:01:29.869625

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '182343089be2'
down_revision: Union[str, None] = '3d919b2a4ccb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expenses', sa.Column('expense_date', sa.Date(), nullable=False))
    op.drop_column('expenses', 'date')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expenses', sa.Column('date', sa.DATE(), autoincrement=False, nullable=False))
    op.drop_column('expenses', 'expense_date')
    # ### end Alembic commands ###
